### ISSUE TITLE
Decouple font size from tile width/height

### ISSUE THREAD

**Issue by grahambates** [asimilon/font2png#4]
First of all thanks for this tool! it's really useful and I'd been considering something similar for a while. I have a suggestion which I wanted to run past you before implementing.

Currently the `width` option dictates both the font size and height of the tile. There is an implied assumption that a glyph for font size 'x' will fit inside an x*x pixel bounding box. This is somewhat true for height (although some fonts do extend beyond this) but point size has no relationship to glyph width in proportional fonts. What's more, a common requirement would be for the image width to be a multiple of 16 for blitting. For example I might want a 16x14 tile for a 14px font.

I can see that you introduced the scale option to somewhat address this need but to me it makes sense to allow the user to specify the width, height and font size separately. They can still default to a single value if not specified. I'm happy to create a PR to add these options if you agree with the approach.

**Comment by asimilon** [comment]
That sounds like a great addition.

Perhaps could work like this:

Get rid of the `scale` parameter.
Add new `size` and `height` parameters, make them so that without being specified they are derived from the `width` parameter similarly to how it works at the moment.

Does that make sense as a way to proceed?

ps. thanks for the changes you've made and catching the mistakes I made :)

**Comment by grahambates** [comment]
Yeah that sounds good. I'm wondering if it makes more sense to derive the `width` and `height` from the `size` option by default, rather than `width` being the primary option as it is currently.

Another idea is that we could round up the width to a mutiple of 16 when deriving it if we agree that our primary target is the Amiga blitter. I suppose mutliples of 8 might make sense too if using `move.b` for fixed width fonts.

**Comment by asimilon** [comment]
Sounds good.  I would suggest that if the derived width < 8 then round up to 8, otherwise stick to multiples of 16, but with no rounding when specifying the width explicitly (Amiga is my target as well, but never know what other platforms people might find this useful for).
